[package]
name = "p0jit"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.106.0"
cranelift-jit = "0.106.0"
cranelift-module = "0.106.0"
cranelift-frontend = "0.106.0"
cranelift-native = "0.106.0"